# Generated by Django 3.1.4 on 2021-01-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210109_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_value',
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
