# Generated by Django 3.1.4 on 2021-01-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210109_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
